// src/init/render.ts — Render InitAnswers into a yaml config string.
// Pure function so it's trivially testable without spinning up ink.

import type { InitAnswers } from "./wizard.js";

const HEADER = `# ~/.isotopes/isotopes.yaml
# Generated by \`isotopes init\`. See isotopes.example.yaml in the repo
# (https://github.com/GhostComplex/isotopes) for the full set of options.
`;

const PROVIDER_SKIP = `# provider:
#   type: anthropic
#   model: claude-opus-4.6
#   apiKey: \${ANTHROPIC_API_KEY}
`;

function renderProvider(answers: InitAnswers): string {
  if (answers.llm !== "ghc-proxy" || !answers.ghcProxy) return PROVIDER_SKIP;
  const { baseUrl, apiKey, model } = answers.ghcProxy;
  return `provider:
  type: anthropic-proxy
  baseUrl: ${baseUrl}
  apiKey: ${apiKey}
  model: ${model}
`;
}

const TOOLS = `tools:
  cli: false                # Shell execution (turn on once you trust the agent)
  fs:
    workspaceOnly: true     # File tools restricted to the agent's workspace
`;

const AGENTS = `agents:
  - id: main
`;

function renderChannels(answers: InitAnswers): string {
  if (answers.channel !== "discord" || !answers.discord) return "";
  const { token, dmPolicy, dmUserId, groupPolicy, groupAllowlist } = answers.discord;

  const dmBlock = dmPolicy === "allowlist" && dmUserId
    ? `        dmAccess:
          policy: allowlist
          allowlist:
            - "${dmUserId}"
`
    : `        dmAccess:
          policy: disabled
`;

  let groupBlock: string;
  if (groupPolicy === "allowlist" && groupAllowlist?.length) {
    const guildIds = new Set<string>();
    const channelIds: string[] = [];
    for (const entry of groupAllowlist) {
      const [guildId, channelId] = entry.split("/");
      guildIds.add(guildId);
      if (channelId) channelIds.push(channelId);
    }
    const guildLines = [...guildIds].map((id) => `            - "${id}"`).join("\n");
    const channelLines = channelIds.map((id) => `            - "${id}"`).join("\n");
    groupBlock = `        groupAccess:
          policy: allowlist
          guildAllowlist:
${guildLines}
`;
    if (channelLines.length > 0) {
      groupBlock += `          channelAllowlist:
${channelLines}
`;
    }
  } else {
    groupBlock = `        groupAccess:
          policy: ${groupPolicy}
`;
  }

  return `
channels:
  discord:
    accounts:
      main:
        token: ${token}
        defaultAgentId: main
${dmBlock}${groupBlock}        threadBindings:
          enabled: true
`;
}

function renderSubagent(answers: InitAnswers): string {
  if (!answers.subagent?.enabled) return "";
  const { claude } = answers.subagent;
  const lines = [
    "subagent:",
    "  enabled: true",
    "  defaultAgent: main",
    "  allowedAgents:",
    "    - main",
  ];
  if (claude) {
    lines.push("  claude:");
    lines.push(`    authToken: ${claude.authToken}`);
    lines.push(`    baseUrl: ${claude.baseUrl}`);
    if (claude.pathToClaudeCodeExecutable) {
      lines.push(`    pathToClaudeCodeExecutable: ${claude.pathToClaudeCodeExecutable}`);
    }
  }
  return lines.join("\n") + "\n";
}

export function renderConfig(answers: InitAnswers): string {
  return [HEADER, renderProvider(answers), TOOLS, AGENTS, renderChannels(answers), renderSubagent(answers)]
    .filter((s) => s.length > 0)
    .join("\n");
}
