import type { InitAnswers } from "./wizard.js";

const HEADER = `# ~/.isotopes/isotopes.yaml
# Generated by \`isotopes init\`. See isotopes.example.yaml in the repo
# (https://github.com/GhostComplex/isotopes) for the full set of options.
`;

const PROVIDER_SKIP = `# provider:
#   type: github-copilot
#   defaultModel: claude-opus-4.7
#   apiKey: \${GITHUB_TOKEN}
`;

function renderProvider(answers: InitAnswers): string {
  if (answers.llm !== "ghc-proxy" || !answers.ghcProxy) return PROVIDER_SKIP;
  const { baseUrl, apiKey, model } = answers.ghcProxy;
  return `provider:
  type: github-copilot
  baseUrl: ${baseUrl}
  apiKey: ${apiKey}
  defaultModel: ${model}
`;
}

function renderAgents(answers: InitAnswers): string {
  const lines = [`agents:`, `  - id: main`];
  if (answers.codingAgent === "claude") {
    lines.push(`  - id: coding`, `    runner: claude`, `    spawnable: true`);
  }
  return lines.join("\n") + "\n";
}

function renderChannels(answers: InitAnswers): string {
  if (answers.channel !== "discord" || !answers.discord) return "";
  const { token, dmPolicy, dmUserId, groupPolicy, groupAllowlist } = answers.discord;

  const dmBlock = dmPolicy === "allowlist" && dmUserId
    ? `        dmAccess:
          policy: allowlist
          allowlist:
            - "${dmUserId}"
`
    : `        dmAccess:
          policy: disabled
`;

  let groupBlock: string;
  if (groupPolicy === "allowlist" && groupAllowlist?.length) {
    // Wizard guarantees entries are uniformly "guildId" OR uniformly "guildId/channelId" — never mixed.
    // The two shapes map to mutually exclusive output lists; emitting both
    // would over-restrict under the AND semantics of allowlist resolution.
    const isChannelMode = groupAllowlist[0].includes("/");
    if (isChannelMode) {
      const channelIds = groupAllowlist
        .map((entry) => entry.split("/")[1])
        .filter((id): id is string => Boolean(id));
      const lines = channelIds.map((id) => `            - "${id}"`).join("\n");
      groupBlock = `        groupAccess:
          policy: allowlist
          channelAllowlist:
${lines}
`;
    } else {
      const lines = groupAllowlist.map((id) => `            - "${id}"`).join("\n");
      groupBlock = `        groupAccess:
          policy: allowlist
          guildAllowlist:
${lines}
`;
    }
  } else {
    groupBlock = `        groupAccess:
          policy: ${groupPolicy}
`;
  }

  return `
channels:
  discord:
    accounts:
      main:
        token: ${token}
        defaultAgentId: main
${dmBlock}${groupBlock}`;
}

export function renderConfig(answers: InitAnswers): string {
  return [HEADER, renderProvider(answers), renderAgents(answers), renderChannels(answers)]
    .filter((s) => s.length > 0)
    .join("\n");
}
