import type { InitAnswers } from "./types.js";

const HEADER = `# ~/.isotopes/isotopes.yaml
# Generated by \`isotopes init\`. See isotopes.example.yaml in the repo
# (https://github.com/GhostComplex/isotopes) for the full set of options.
`;

const PROVIDER_SKIP = `# provider:
#   type: minimax-cn          # or "minimax" for the international endpoint
#   defaultModel: MiniMax-M2.7
#   apiKey: \${MINIMAX_API_KEY}
`;

function formatProvider(answers: InitAnswers): string {
  const { provider } = answers;
  if (provider.type === "ghc-proxy") {
    return `provider:
  type: github-copilot
  baseUrl: ${provider.baseUrl}
  apiKey: ${provider.apiKey}
  defaultModel: ${provider.model}
`;
  }
  if (provider.type === "minimax-cn") {
    return `provider:
  type: minimax-cn
  apiKey: ${provider.apiKey}
  defaultModel: ${provider.model}
`;
  }
  return PROVIDER_SKIP;
}

function formatAgents(answers: InitAnswers): string {
  const lines = [`agents:`, `  - id: main`];
  if (answers.codingAgent === "claude") {
    lines.push(`  - id: coding`, `    runner: claude`, `    spawnable: true`);
  }
  return lines.join("\n") + "\n";
}

function formatChannels(answers: InitAnswers): string {
  if (answers.channel.type !== "discord") return "";
  const { token, dmPolicy, dmUserId, groupPolicy, groupAllowlist } = answers.channel;

  const dmBlock = dmPolicy === "allowlist" && dmUserId
    ? `        dmAccess:
          policy: allowlist
          allowlist:
            - "${dmUserId}"
`
    : `        dmAccess:
          policy: disabled
`;

  let groupBlock: string;
  if (groupPolicy === "allowlist" && groupAllowlist?.length) {
    // Wizard guarantees entries are uniformly "guildId" OR uniformly "guildId/channelId" — never mixed.
    // The two shapes map to mutually exclusive output lists; emitting both
    // would over-restrict under the AND semantics of allowlist resolution.
    const isChannelMode = groupAllowlist[0].includes("/");
    if (isChannelMode) {
      const channelIds = groupAllowlist
        .map((entry) => entry.split("/")[1])
        .filter((id): id is string => Boolean(id));
      const lines = channelIds.map((id) => `            - "${id}"`).join("\n");
      groupBlock = `        groupAccess:
          policy: allowlist
          channelAllowlist:
${lines}
`;
    } else {
      const lines = groupAllowlist.map((id) => `            - "${id}"`).join("\n");
      const guildEntries = groupAllowlist
        .map((id) => `          "${id}":\n            requireMention: true`)
        .join("\n");
      groupBlock = `        groupAccess:
          policy: allowlist
          guildAllowlist:
${lines}
        guilds:
${guildEntries}
`;
    }
  } else {
    groupBlock = `        groupAccess:
          policy: ${groupPolicy}
`;
  }

  return `
channels:
  discord:
    accounts:
      main:
        token: ${token}
        defaultAgentId: main
${dmBlock}${groupBlock}`;
}

export function toYaml(answers: InitAnswers): string {
  return [HEADER, formatProvider(answers), formatAgents(answers), formatChannels(answers)]
    .filter((s) => s.length > 0)
    .join("\n");
}
